// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a title for a journal entry based on its content.
 *
 * - generateEntryTitle - A function that generates a title for a journal entry.
 * - GenerateEntryTitleInput - The input type for the generateEntryTitle function.
 * - GenerateEntryTitleOutput - The return type for the generateEntryTitle function.
 */

import {ai} from '@/ai/genkit';
import {z}from 'genkit';

const GenerateEntryTitleInputSchema = z.object({
  entryContent: z.string().describe('The content of the journal entry.'),
});
export type GenerateEntryTitleInput = z.infer<typeof GenerateEntryTitleInputSchema>;

const GenerateEntryTitleOutputSchema = z.object({
  title: z.string().describe('The generated title for the journal entry.'),
});
export type GenerateEntryTitleOutput = z.infer<typeof GenerateEntryTitleOutputSchema>;

export async function generateEntryTitle(input: GenerateEntryTitleInput): Promise<GenerateEntryTitleOutput> {
  return generateEntryTitleFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateEntryTitlePrompt',
  input: {schema: GenerateEntryTitleInputSchema},
  output: {schema: GenerateEntryTitleOutputSchema},
  prompt: `You are a journal title generator. Generate a concise and descriptive title (max 10 words) for the following journal entry content:\n\n{{entryContent}}`,
});

const generateEntryTitleFlow = ai.defineFlow(
  {
    name: 'generateEntryTitleFlow',
    inputSchema: GenerateEntryTitleInputSchema,
    outputSchema: GenerateEntryTitleOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
